[Task 130] - Implementação da tela para gestão de Setores
Nocs-lab/Obatala pull request #78
Opened 2024-09-25 11:58 UTC by anaclrra

Este PR adiciona tela para Criar, editar e visualizar setores.

2024-09-25 12:10 UTC, Everbero requested changes

2024-09-25 12:10 UTC, Everbero commented on classes/Admin/Enqueuer.php
@anaclrra  o step editor está sendo removido do plugin

2024-09-25 16:51 UTC, anaclrra commented on classes/Admin/Enqueuer.php
@Everbero Removi o Step editor das classes Enqueuer e AdminMenu.

2024-09-26 11:48 UTC, Everbero approved these changes

2024-09-26 11:49 UTC, Everbero approved these changes

2024-09-26 11:49 UTC, merged